/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LAB_H_RPCGEN
#define _LAB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	float v[10];
	int len;
};
typedef struct operandos operandos;

#define PROG 55000555
#define VERS 110011

#if defined(__STDC__) || defined(__cplusplus)
#define findSmallest 1
extern  float * findsmallest_110011(operandos *, CLIENT *);
extern  float * findsmallest_110011_svc(operandos *, struct svc_req *);
#define findGreatest 2
extern  float * findgreatest_110011(operandos *, CLIENT *);
extern  float * findgreatest_110011_svc(operandos *, struct svc_req *);
extern int prog_110011_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define findSmallest 1
extern  float * findsmallest_110011();
extern  float * findsmallest_110011_svc();
#define findGreatest 2
extern  float * findgreatest_110011();
extern  float * findgreatest_110011_svc();
extern int prog_110011_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LAB_H_RPCGEN */
